### ISSUE TITLE
NFC Implementation

### ISSUE THREAD

**Issue by JamiuJimoh** [JamiuJimoh/HNG_CheckNGo#1]
- Add the necessary dependencies for the NFC implementation.
- Add the necessary configurations ( in the AndroidManifest, Info.plist) or other configs as the case may be.

You're to work on the NFCReadPage.dart and NFCWritePage.dart. Implement and complete the flow. The NFCReadPage already has the data you need passed in.

**Comment by Kellytomi** [comment]
I have implemented the NFC functionality as requested. This includes:
- Adding the necessary dependencies.
- Configuring the required settings in `AndroidManifest.xml` and `Info.plist`.
- Implementing `NFCReadPage.dart` and `NFCWritePage.dart` to complete the NFC read and write flow.

Please review the pull request for these changes: [PR #3](https://github.com/JamiuJimoh/HNG_CheckNGo/pull/3#issue-2433686473)
